# Generated by Django 2.2.1 on 2019-05-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Region', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('TotalSales', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unixtime', models.IntegerField()),
                ('length', models.IntegerField()),
                ('protocol', models.CharField(max_length=16)),
                ('src_port', models.IntegerField()),
                ('dst_port', models.IntegerField()),
                ('src_ip', models.CharField(max_length=39)),
                ('dst_ip', models.CharField(max_length=39)),
                ('sni', models.CharField(max_length=64)),
            ],
        ),
    ]
